### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by taowu1982** [zhuzhenpeng/CTP-TradeServer#1]
工程目录里面的工程文件貌似没上传呢，能告知下maltlab该如何接入么，谢谢了！

**Comment by zhuzhenpeng** [comment]
已经补充了，直接在TradeServer文件夹内找到TradeServer.vcxproj和TradeServer.vcxproj.filters，复制它们的内容即可
matlab和这个程序通过tcp通信，matlab传62字节的数据过来，哪些字节段代表什么提前约定好，这边的程序就可以解析；如果你问matlab如何接入行情，直接的我并不清楚，可以尝试用别的程序接了再给它
