### ISSUE TITLE
Compile problem with noQtCTP

### ISSUE THREAD

**Issue by amandazh** [zhuzhenpeng/CTP-TradeServer#2]
前辈你好
我刚开始学习CTP开发，用codeblocks打开你的noQtCTP以后无法compile,出现以下error:
error tdapi does not name a type. 请问你知道是什么问题吗？我用ctp开发资料的例子也是出现这个问题，明明指针在上一行已经定义，complier却找不到定义，这是为什么？
![error](https://cloud.githubusercontent.com/assets/11388905/8894058/40f29076-33ec-11e5-9502-3aba63a1396e.png)

**Comment by zhuzhenpeng** [comment]
我也不太清楚，你看下以下连接看下有没有帮助：
http://blog.csdn.net/typename/article/details/7173550
http://stackoverflow.com/questions/2133250/does-not-name-a-type-error-in-c
http://stackoverflow.com/questions/4233360/pointer-to-a-object-class-throwing-does-not-name-a-type

不排除我的代码有错误，但我以前是跑得了的；开发资料里文档的代码是官方提供的，应该不会错的，我以前学的时候也没遇到你的问题，建议在Windows平台下就用VS开发。

**Comment by haiwangcat** [comment]
把括号改成花括号试试？

**Comment by amandazh** [comment]
用Visual Studio compile是成功的，谢谢前辈。之后有问题再向你请教。
