### ISSUE TITLE
iOS开发

### ISSUE THREAD

**Issue by frankxiongsir** [zhuzhenpeng/CTP-TradeServer#3]
请教一下iOS应用开发CTP怎么初始化交易接口

**Comment by zhuzhenpeng** [comment]
不懂IOS技术，但官方有IOS的api，下了以后可以看我代码初始化那段，我猜应该差不多的

**Comment by elkhawk** [comment]
请问这个ios的api现在还有吗？ 在上期技术的官网，并没有找到？
